### ISSUE TITLE
Define and maintain an allowlist on the server spec

### ISSUE THREAD

**Issue by chrisguidry** [hordehost/zomboid-operator#12]
The server spec should support an allowlist:

```
spec:
  ...
  allowlist:
  - name: chris
    accessLevel: admin
    password: 
      name: the-name-of-a-secret
      key: the-key-of-a-secret
  - name: spiffo
    accessLevel: user  # the default
    password:
      name: another-secret
      key: my-password-key
```

Reconciling this could add a status allowlist entry showing the current users:

```
status:
  allowlist:
  - name: chris
    accessLevel: user  # would signal a change was needed
    hash: <password hash>
  - name: spiffo
    accessLevel: user
    hash: <password hash>
```

There doesn't appear to be a way to read the allowlist (at least in 41.78), so we either need a way to peek into the sqlite database at `/game-data/db/<server-name>.db`, or we would maintain the allowlist in the `status` incrementally as we added or removed users.  This will work as long as we can rely on the K8s API to keep the `status` permanently, which it should.

It may be worth getting sqlite into the image anyway in case there are other useful bits in there.
