### ISSUE TITLE
Changing permissions on the `/game-data` directory automatically with an `initContainer`

### ISSUE THREAD

**Issue by chrisguidry** [hordehost/zomboid-operator#2]
I hit a roadblock running this on a real cluster because the filesystem on the PV (provisioned by rook) was owned by `root`.  Should add a small `initContainer` running as root to grant permissions to the `spiffo` (1000:1000) user.

This seemed to be good enough:
```
initContainers:
- name: permissions-init
  image: busybox
  command:
  - /bin/sh
  - -c
  - chown -R 1000:1000 /game-data && chmod -R 755 /game-data
  volumeMounts:
  - name: game-data
    mountPath: /game-data
```
